
disabled_rules:
- trailing_whitespace
opt_in_rules:
excluded:
- Carthage
- Pods
- SwiftLint/Common/3rdPartyLib
nesting:
    type_level:
        warning: 3
        error: 6
line_length:
    warning: 300
    error: 400
    ignores_function_declarations: true
    ignores_comments: true
    ignores_urls: true
function_body_length:
    warning: 300
    error: 500
function_parameter_count:
    warning: 6
    error: 8
type_body_length:
    warning: 300
    error: 500
file_length:
    warning: 400
    error: 500
    ignore_comment_only_lines: true
cyclomatic_complexity:
    warning: 15
    error: 25
reporter: "xcode"
